routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\SubmenuController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\UserMenuController;
use App\Http\Controllers\UserRoleController;
use App\Http\Controllers\FinanceCoaController;
use App\Http\Controllers\UserProfileController;
use App\Http\Controllers\UserSubMenuController;
use App\Http\Controllers\FinanceBudgetController;
use App\Http\Controllers\FinanceTransactionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// buatan
Route::get('/role/{role}/access', [UserRoleController::class, 'access']);
Route::post('profile/reset/{id}', [UserProfileController::class, 'resetProfile']);
Route::get('profile/change-password', [UserProfileController::class, 'changePassword'])->name('change-password.index');
Route::patch('profile/change-password/{id}', [UserProfileController::class, 'changeProccess'])->name('profile.change-password');

// // resource
Route::resource('user', UserController::class);
Route::resource('menu', UserMenuController::class);
Route::resource('submenu', UserSubMenuController::class);
Route::resource('role', UserRoleController::class);
Route::resource('profile', UserProfileController::class);
Route::resource('employees', EmployeeController::class);
Route::resource('products', ProductController::class);
Route::resource('clients', ClientController::class);
Route::resource('finance-coas', FinanceCoaController::class);
Route::resource('finance-budgets', FinanceBudgetController::class);
Route::resource('finance-transactions', FinanceTransactionController::class);

app/Http/Controllers/FinanceTransactionController.php
<?php

namespace App\Http\Controllers;

use App\Models\FinanceTransaction;
use Illuminate\Http\Request;

/**
 * Class FinanceTransactionController
 * @package App\Http\Controllers
 */
class FinanceTransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $financeTransactions = FinanceTransaction::paginate();

        return view('finance-transaction.index', compact('financeTransactions'))
            ->with('i', (request()->input('page', 1) - 1) * $financeTransactions->perPage());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $financeTransaction = new FinanceTransaction();
        return view('finance-transaction.create', compact('financeTransaction'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate(FinanceTransaction::$rules);

        $financeTransaction = FinanceTransaction::create($request->all());

        return redirect()->route('finance-transactions.index')
            ->with('success', 'FinanceTransaction created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $financeTransaction = FinanceTransaction::find($id);

        return view('finance-transaction.show', compact('financeTransaction'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $financeTransaction = FinanceTransaction::find($id);

        return view('finance-transaction.edit', compact('financeTransaction'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  FinanceTransaction $financeTransaction
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, FinanceTransaction $financeTransaction)
    {
        request()->validate(FinanceTransaction::$rules);

        $financeTransaction->update($request->all());

        return redirect()->route('finance-transactions.index')
            ->with('success', 'FinanceTransaction updated successfully');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $financeTransaction = FinanceTransaction::find($id)->delete();

        return redirect()->route('finance-transactions.index')
            ->with('success', 'FinanceTransaction deleted successfully');
    }
}

resources/views/finance-transaction/create.blade.php
@extends('layouts.main')
@section('title', __('Finance Transaction'))
@section('content')
<!--begin::Main-->
	<div class="d-flex flex-column flex-column-fluid">
		<!--begin::toolbar-->
		<div class="toolbar" id="kt_toolbar">
			<div class="container d-flex flex-stack flex-wrap flex-sm-nowrap">
				<!--begin::Info-->
				<div class="d-flex flex-column align-items-start justify-content-center flex-wrap me-1">
					<!--begin::Title-->
					<h3 class="text-dark fw-bolder my-1">{{ __('Finance Transaction') }}</h3>
					<!--end::Title-->
					<!--begin::Breadcrumb-->
					<ul class="breadcrumb breadcrumb-line bg-transparent text-muted fw-bold p-0 my-1 fs-7">
						<li class="breadcrumb-item">
							<a href="{{ url('') }}" class="text-muted text-hover-primary">Home</a>
						</li>
						<li class="breadcrumb-item">
							<a href="{{ route('finance-transactions.index') }}" class="text-muted text-hover-primary">{{ __('Finance Transaction') }}</a>
						</li>
						<li class="breadcrumb-item text-dark">Create</li>
					</ul>
					<!--end::Breadcrumb-->
				</div>
				<!--end::Info-->
			</div>
		</div>
		<!--end::toolbar-->
		<!--begin::Content-->
		<div class="content fs-6 d-flex flex-column-fluid mt-5" id="kt_content">
			<!--begin::Container-->
			<div class="container">

                @includeif('partials.errors')

				<!--begin::Profile Account-->
				<div class="card" >
					<div class="card-body">
                        <form method="POST" action="{{ route('finance-transactions.store') }}"  role="form" enctype="multipart/form-data">
							@csrf
							
							@include('finance-transaction.form')

						</form>
					</div>
					</div>
				<!--end::Profile Account-->
			</div>
			<!--end::Container-->
		</div>
		<!--end::Content-->
	</div>
<!--end::Main-->
@endsection

resources/views/finance-transaction/edit.blade.php
@extends('layouts.main')
@section('title', __('Finance Transaction'))
@section('content')
    <!--begin::Main-->
	<div class="d-flex flex-column flex-column-fluid">
		<!--begin::toolbar-->
		<div class="toolbar" id="kt_toolbar">
			<div class="container d-flex flex-stack flex-wrap flex-sm-nowrap">
				<!--begin::Info-->
				<div class="d-flex flex-column align-items-start justify-content-center flex-wrap me-1">
					<!--begin::Title-->
					<h3 class="text-dark fw-bolder my-1">{{ __('Finance Transaction') }}</h3>
					<!--end::Title-->
					<!--begin::Breadcrumb-->
					<ul class="breadcrumb breadcrumb-line bg-transparent text-muted fw-bold p-0 my-1 fs-7">
						<li class="breadcrumb-item">
							<a href="{{ url('') }}" class="text-muted text-hover-primary">Home</a>
						</li>
						<li class="breadcrumb-item">
							<a href="{{ route('finance-transactions.index') }}" class="text-muted text-hover-primary">{{ __('Finance Transaction') }}</a>
						</li>
						<li class="breadcrumb-item text-dark">Create</li>
					</ul>
					<!--end::Breadcrumb-->
				</div>
				<!--end::Info-->
			</div>
		</div>
		<!--end::toolbar-->
		<!--begin::Content-->
		<div class="content fs-6 d-flex flex-column-fluid mt-5" id="kt_content">
			<!--begin::Container-->
			<div class="container">

                @includeif('partials.errors')

				<!--begin::Profile Account-->
				<div class="card" >
					<div class="card-body">
                        <form method="POST" action="{{ route('finance-transactions.update', $financeTransaction->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('finance-transaction.form')

                        </form>
					</div>
					</div>
				<!--end::Profile Account-->
			</div>
			<!--end::Container-->
		</div>
		<!--end::Content-->
	</div>
<!--end::Main-->
@endsection

resources/views/finance-transaction/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">
        
        <div class="form-group mb-3">
            {{ Form::label('nomor_voucher') }}
            {{ Form::text('nomor_voucher', $financeTransaction->nomor_voucher, ['class' => 'form-control' . ($errors->has('nomor_voucher') ? ' is-invalid' : ''), 'placeholder' => 'Nomor Voucher']) }}
            {!! $errors->first('nomor_voucher', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group mb-3">
            {{ Form::label('total_debit') }}
            {{ Form::text('total_debit', $financeTransaction->total_debit, ['class' => 'form-control' . ($errors->has('total_debit') ? ' is-invalid' : ''), 'placeholder' => 'Total Debit']) }}
            {!! $errors->first('total_debit', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group mb-3">
            {{ Form::label('total_kredit') }}
            {{ Form::text('total_kredit', $financeTransaction->total_kredit, ['class' => 'form-control' . ($errors->has('total_kredit') ? ' is-invalid' : ''), 'placeholder' => 'Total Kredit']) }}
            {!! $errors->first('total_kredit', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group mb-3">
            {{ Form::label('tanggal') }}
            {{ Form::text('tanggal', $financeTransaction->tanggal, ['class' => 'form-control' . ($errors->has('tanggal') ? ' is-invalid' : ''), 'placeholder' => 'Tanggal']) }}
            {!! $errors->first('tanggal', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group mb-3">
            {{ Form::label('keterangan') }}
            {{ Form::text('keterangan', $financeTransaction->keterangan, ['class' => 'form-control' . ($errors->has('keterangan') ? ' is-invalid' : ''), 'placeholder' => 'Keterangan']) }}
            {!! $errors->first('keterangan', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group mb-3">
            {{ Form::label('pembuat') }}
            {{ Form::text('pembuat', $financeTransaction->pembuat, ['class' => 'form-control' . ($errors->has('pembuat') ? ' is-invalid' : ''), 'placeholder' => 'Pembuat']) }}
            {!! $errors->first('pembuat', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group mb-3">
            {{ Form::label('id_akun') }}
            {{ Form::text('id_akun', $financeTransaction->id_akun, ['class' => 'form-control' . ($errors->has('id_akun') ? ' is-invalid' : ''), 'placeholder' => 'Id Akun']) }}
            {!! $errors->first('id_akun', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group mb-3">
            {{ Form::label('tipe_akun') }}
            {{ Form::text('tipe_akun', $financeTransaction->tipe_akun, ['class' => 'form-control' . ($errors->has('tipe_akun') ? ' is-invalid' : ''), 'placeholder' => 'Tipe Akun']) }}
            {!! $errors->first('tipe_akun', '<div class="invalid-feedback">:message</div>') !!}
        </div>

    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>

resources/views/finance-transaction/index.blade.php
@extends('layouts.main')
@section('title', __('Finance Transaction'))
@section('content')
    <!--begin::Main-->
	<div class="d-flex flex-column flex-column-fluid">
		<!--begin::toolbar-->
		<div class="toolbar" id="kt_toolbar">
			<div class="container d-flex flex-stack flex-wrap flex-sm-nowrap">
				<!--begin::Info-->
				<div class="d-flex flex-column align-items-start justify-content-center flex-wrap me-1">
					
					<!--begin::Breadcrumb-->
					<ul class="breadcrumb breadcrumb-line bg-transparent text-muted fw-bold p-0 my-1 fs-7">
						<li class="breadcrumb-item">
							<a href="{{ route('finance-transactions.index') }}" class="text-muted text-hover-primary">{{ __('Finance Transaction') }}</a>
						</li>
						<li class="breadcrumb-item text-dark">{{ __('Finance Transaction') }}</li>							
					</ul>
					<!--end::Breadcrumb-->
				</div>
				<!--end::Info-->
				
				
			</div>
		</div>
		<!--end::toolbar-->
		<!--begin::Content-->
		<div class="content fs-6 d-flex flex-column-fluid mt-5" id="kt_content">
			<!--begin::Container-->
			<div class="container">
				<!--begin::Profile Account-->
				<div class="card" >
					<div class="card-body">
						<!--begin::Alert-->                                        
					
					<!--end::Alert-->
						<div class="table-responsive">
							<a href="{{ route('finance-transactions.create') }}" class="btn btn-primary mb-3" >Tambah {{ __('Finance Transaction') }} Baru</a>
							@if ($message = Session::get('success'))
                                <div class="alert alert-success">
                                    <p>{{ $message }}</p>
                                </div>
                            @endif
							<table class="table table-striped table-hover gy-7 gs-7 text-center">
								<thead>
									<tr class="fw-bold fs-6 text-gray-800 border-bottom-2 border-gray-200">
										<th>No</th>
										
										<th>Nomor Voucher</th>
										<th>Total Debit</th>
										<th>Total Kredit</th>
										<th>Tanggal</th>
										<th>Keterangan</th>
										<th>Pembuat</th>
										<th>Id Akun</th>
										<th>Tipe Akun</th>

										<th>Aksi</th>
									</tr>
								</thead>
								<tbody>                                                 
                                    @foreach ($financeTransactions as $financeTransaction)
                                        <tr>
                                            <td>{{ ++$i }}</td>
                                            
											<td>{{ $financeTransaction->nomor_voucher }}</td>
											<td>{{ $financeTransaction->total_debit }}</td>
											<td>{{ $financeTransaction->total_kredit }}</td>
											<td>{{ $financeTransaction->tanggal }}</td>
											<td>{{ $financeTransaction->keterangan }}</td>
											<td>{{ $financeTransaction->pembuat }}</td>
											<td>{{ $financeTransaction->id_akun }}</td>
											<td>{{ $financeTransaction->tipe_akun }}</td>

                                            <td>
                                                <form action="{{ route('finance-transactions.destroy',$financeTransaction->id) }}" method="POST">
                                                    <a class="btn btn-sm btn-primary " href="{{ route('finance-transactions.show',$financeTransaction->id) }}"><i class="fa fa-fw fa-eye"></i> Show</a>
                                                    <a class="btn btn-sm btn-success" href="{{ route('finance-transactions.edit',$financeTransaction->id) }}"><i class="fa fa-fw fa-edit"></i> Edit</a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger btn-sm btn-delete"><i class="fa fa-fw fa-trash"></i> Delete</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
								</tbody>
							</table>
						</div>
					</div>
                </div>
				<!--end::Profile Account-->
			</div>
			<!--end::Container-->
		</div>
		<!--end::Content-->
	</div>
	<!--end::Main-->
@endsection

@section('scripts')
	<script type="text/javascript">


		$('body').on('click', '.btn-delete', function(event) {
			event.preventDefault();

			var form = $(this).closest('form');

			Swal.fire({
				title: 'Are you sure?',
				text: "You won't be able to revert this!",
				icon: 'warning',
				showCancelButton: true,
				confirmButtonColor: '#3085d6',
				cancelButtonColor: '#d33',
				confirmButtonText: 'Yes, delete it!'
			}).then((result) => {
				if (result.isConfirmed) {
					form.submit();
				}
			})


		})

		

	</script>
@endsection

resources/views/finance-transaction/show.blade.php
@extends('layouts.main')
@section('title', __('Finance Transaction'))
@section('content')
<!--begin::Main-->
	<div class="d-flex flex-column flex-column-fluid">
		<!--begin::toolbar-->
		<div class="toolbar" id="kt_toolbar">
			<div class="container d-flex flex-stack flex-wrap flex-sm-nowrap">
				<!--begin::Info-->
				<div class="d-flex flex-column align-items-start justify-content-center flex-wrap me-1">
					
					<!--begin::Breadcrumb-->
					<ul class="breadcrumb breadcrumb-line bg-transparent text-muted fw-bold p-0 my-1 fs-7">
						<li class="breadcrumb-item">
							<a href="{{ route('finance-transactions.index') }}" class="text-muted text-hover-primary">{{ __('Finance Transaction') }}</a>
						</li>
						<li class="breadcrumb-item text-dark">{{ __('Finance Transaction') }}</li>							
					</ul>
					<!--end::Breadcrumb-->
				</div>
				<!--end::Info-->
				
				
			</div>
		</div>
		<!--end::toolbar-->
		<!--begin::Content-->
		<div class="content fs-6 d-flex flex-column-fluid mt-5" id="kt_content">
			<!--begin::Container-->
			<div class="container">
				<!--begin::Profile Account-->
                <div class="card">
                    <div class="card-header">
                        <div class="float-left mt-4">
                            <span class="card-title">Show Finance Transaction</span>
                        </div>
                        <div class="float-right mt-4">
                            <a class="btn btn-primary" href="{{ route('finance-transactions.index') }}"> Back</a>
                        </div>
                    </div>

                    <div class="card-body">
                        
                        <div class="form-group">
                            <strong>Nomor Voucher:</strong>
                            {{ $financeTransaction->nomor_voucher }}
                        </div>
                        <div class="form-group">
                            <strong>Total Debit:</strong>
                            {{ $financeTransaction->total_debit }}
                        </div>
                        <div class="form-group">
                            <strong>Total Kredit:</strong>
                            {{ $financeTransaction->total_kredit }}
                        </div>
                        <div class="form-group">
                            <strong>Tanggal:</strong>
                            {{ $financeTransaction->tanggal }}
                        </div>
                        <div class="form-group">
                            <strong>Keterangan:</strong>
                            {{ $financeTransaction->keterangan }}
                        </div>
                        <div class="form-group">
                            <strong>Pembuat:</strong>
                            {{ $financeTransaction->pembuat }}
                        </div>
                        <div class="form-group">
                            <strong>Id Akun:</strong>
                            {{ $financeTransaction->id_akun }}
                        </div>
                        <div class="form-group">
                            <strong>Tipe Akun:</strong>
                            {{ $financeTransaction->tipe_akun }}
                        </div>

                    </div>
                </div>
            <!--end::Profile Account-->
			</div>
			<!--end::Container-->
		</div>
		<!--end::Content-->
	</div>
	<!--end::Main-->
@endsection